// <auto-generated />
using System;
using MeuProjetoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeuProjetoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251103212139_AddExperienciaEEscolaridade")]
    partial class AddExperienciaEEscolaridade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Escolaridade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AnoConclusao")
                        .HasColumnType("int");

                    b.Property<int?>("AnoInicio")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("FkInstituicaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkPessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCurso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FkInstituicaoId");

                    b.HasIndex("FkPessoaId");

                    b.ToTable("Escolaridades");
                });

            modelBuilder.Entity("MeuProjetoApi.Models.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FkPessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("bit");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FkPessoaId");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("MeuProjetoApi.Models.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("MeuProjetoApi.Models.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FkPessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("bit");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FkPessoaId");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("MeuProjetoApi.Models.ExperienciaProfissional", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AnoEntrada")
                        .HasColumnType("int");

                    b.Property<int?>("AnoSaida")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FkEmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkPessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FkEmpresaId");

                    b.HasIndex("FkPessoaId");

                    b.ToTable("ExperienciasProfissionais");
                });

            modelBuilder.Entity("MeuProjetoApi.Models.Funcao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Funcoes");
                });

            modelBuilder.Entity("MeuProjetoApi.Models.Instituicao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instituicoes");
                });

            modelBuilder.Entity("MeuProjetoApi.Models.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CpfCriptografado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CpfHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CpfHash")
                        .IsUnique();

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("MeuProjetoApi.Models.PessoaFuncao", b =>
                {
                    b.Property<Guid>("FkPessoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkFuncaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkSetorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FkPessoaId", "FkFuncaoId", "FkSetorId");

                    b.HasIndex("FkFuncaoId");

                    b.HasIndex("FkSetorId");

                    b.ToTable("PessoaFuncoes");
                });

            modelBuilder.Entity("MeuProjetoApi.Models.Setor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("Escolaridade", b =>
                {
                    b.HasOne("MeuProjetoApi.Models.Instituicao", "Instituicao")
                        .WithMany("EscolaridadesAssociadas")
                        .HasForeignKey("FkInstituicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeuProjetoApi.Models.Pessoa", "Pessoa")
                        .WithMany("Escolaridades")
                        .HasForeignKey("FkPessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instituicao");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("MeuProjetoApi.Models.Contato", b =>
                {
                    b.HasOne("MeuProjetoApi.Models.Pessoa", "Pessoa")
                        .WithMany("Contatos")
                        .HasForeignKey("FkPessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("MeuProjetoApi.Models.Endereco", b =>
                {
                    b.HasOne("MeuProjetoApi.Models.Pessoa", "Pessoa")
                        .WithMany("Enderecos")
                        .HasForeignKey("FkPessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("MeuProjetoApi.Models.ExperienciaProfissional", b =>
                {
                    b.HasOne("MeuProjetoApi.Models.Empresa", "Empresa")
                        .WithMany("ExperienciasAssociadas")
                        .HasForeignKey("FkEmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeuProjetoApi.Models.Pessoa", "Pessoa")
                        .WithMany("Experiencias")
                        .HasForeignKey("FkPessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("MeuProjetoApi.Models.PessoaFuncao", b =>
                {
                    b.HasOne("MeuProjetoApi.Models.Funcao", "Funcao")
                        .WithMany("PessoasFuncoes")
                        .HasForeignKey("FkFuncaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeuProjetoApi.Models.Pessoa", "Pessoa")
                        .WithMany("PessoasFuncoes")
                        .HasForeignKey("FkPessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeuProjetoApi.Models.Setor", "Setor")
                        .WithMany("PessoasFuncoes")
                        .HasForeignKey("FkSetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcao");

                    b.Navigation("Pessoa");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("MeuProjetoApi.Models.Empresa", b =>
                {
                    b.Navigation("ExperienciasAssociadas");
                });

            modelBuilder.Entity("MeuProjetoApi.Models.Funcao", b =>
                {
                    b.Navigation("PessoasFuncoes");
                });

            modelBuilder.Entity("MeuProjetoApi.Models.Instituicao", b =>
                {
                    b.Navigation("EscolaridadesAssociadas");
                });

            modelBuilder.Entity("MeuProjetoApi.Models.Pessoa", b =>
                {
                    b.Navigation("Contatos");

                    b.Navigation("Enderecos");

                    b.Navigation("Escolaridades");

                    b.Navigation("Experiencias");

                    b.Navigation("PessoasFuncoes");
                });

            modelBuilder.Entity("MeuProjetoApi.Models.Setor", b =>
                {
                    b.Navigation("PessoasFuncoes");
                });
#pragma warning restore 612, 618
        }
    }
}
